// Type Imports
import type { Contact } from '@/types/apps/contact-types'

export const db: Contact[] = [
  {
    firstName: 'John',
    lastName: 'Doe',
    image: '/images/avatars/avatar-1.webp',
    email: 'john.doe@example.com',
    phone: 9834567890,
    city: 'New York',
    notes: 'Primary account lead from the Q1 outreach campaign.',
    addedDate: new Date('2024-01-15'),
    labels: ['lead', 'customer'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Sarah',
    lastName: 'Doe',
    image: '/images/avatars/avatar-2.webp',
    email: 'sarah.doe@example.com',
    phone: 7894567890,
    city: 'Los Angeles',
    notes: 'VIP client — prefers email follow-ups on Tuesday mornings.',
    addedDate: new Date('2024-03-22'),
    labels: ['customer', 'vip'],
    status: 'active',
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Michael',
    lastName: 'Smith',
    image: '/images/avatars/avatar-3.webp',
    email: 'michael.smith@example.com',
    phone: 6834567890,
    city: 'Chicago',
    notes: 'Blocked after repeated unsolicited outreach attempts.',
    addedDate: new Date('2023-06-08'),
    labels: ['partner'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: true,
    isSpam: false
  },
  {
    firstName: 'Emma',
    lastName: 'Wilson',
    image: '/images/avatars/avatar-4.webp',
    email: 'emma.wilson@example.com',
    phone: 6534567890,
    city: 'San Francisco',
    notes: 'Key supplier contact for the west coast distribution team.',
    addedDate: new Date('2024-08-03'),
    labels: ['supplier'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'David',
    lastName: 'Kim',
    image: '/images/avatars/avatar-5.webp',
    email: 'david.kim@example.com',
    phone: 7434567890,
    city: 'Seattle',
    notes: 'Marked as spam — suspicious bulk messaging activity.',
    addedDate: new Date('2024-11-17'),
    labels: ['freelancer'],
    status: 'prospect',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: true
  },
  {
    firstName: 'Aron',
    lastName: 'Thompson',
    image: '/images/avatars/avatar-6.webp',
    email: 'aron.thompson@example.com',
    phone: 8534567890,
    city: 'Miami',
    notes: 'Long-term VIP partner referred by the enterprise sales team.',
    addedDate: new Date('2025-02-10'),
    labels: ['lead', 'vip'],
    status: 'active',
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    image: '/images/avatars/avatar-7.webp',
    email: 'alice.johnson@example.com',
    phone: 7534567890,
    city: 'Boston',
    notes: 'Renewed annual support contract in April.',
    addedDate: new Date('2024-04-29'),
    labels: ['customer'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'James',
    lastName: 'Martinez',
    image: '/images/avatars/avatar-8.webp',
    email: 'james.martinez@example.com',
    phone: 6123456789,
    city: 'Austin',
    notes: 'Favourite lead — scheduled demo for the analytics module.',
    addedDate: new Date('2023-05-14'),
    labels: ['lead'],
    status: 'active',
    isFavourite: true,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Olivia',
    lastName: 'Brown',
    image: '/images/avatars/avatar-9.webp',
    email: 'olivia.brown@example.com',
    phone: 5123456789,
    city: 'Denver',
    notes: 'Inactive partner account pending contract renegotiation.',
    addedDate: new Date('2023-09-21'),
    labels: ['partner'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Noah',
    lastName: 'Davis',
    image: '/images/avatars/avatar-10.webp',
    email: 'noah.davis@example.com',
    phone: 4123456789,
    city: 'Portland',
    notes: 'Freelance designer — prospect for the brand refresh project.',
    addedDate: new Date('2024-12-05'),
    labels: ['freelancer'],
    status: 'prospect',
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Sophia',
    lastName: 'Garcia',
    image: '/images/avatars/avatar-11.webp',
    email: 'sophia.garcia@example.com',
    phone: 3123456789,
    city: 'Phoenix',
    notes: 'VIP supplier with priority shipping terms.',
    addedDate: new Date('2024-07-18'),
    labels: ['supplier', 'vip'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Liam',
    lastName: 'Anderson',
    image: '/images/avatars/avatar-12.webp',
    email: 'liam.anderson@example.com',
    phone: 2123456789,
    city: 'Dallas',
    notes: 'Joint lead and partner contact for the co-marketing initiative.',
    addedDate: new Date('2023-10-30'),
    labels: ['lead', 'partner'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Mia',
    lastName: 'Taylor',
    image: '/images/avatars/avatar-13.webp',
    email: 'mia.taylor@example.com',
    phone: 9123456780,
    city: 'Nashville',
    notes: 'Inactive customer — paused subscription until Q3.',
    addedDate: new Date('2025-01-07'),
    labels: ['customer'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Ethan',
    lastName: 'Moore',
    image: '/images/avatars/avatar-14.webp',
    email: 'ethan.moore@example.com',
    phone: 8123456780,
    city: 'Atlanta',
    notes: 'Prospect VIP — evaluating enterprise plan options.',
    addedDate: new Date('2025-03-03'),
    labels: ['vip'],
    status: 'prospect',
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Charlotte',
    lastName: 'Lee',
    image: '/images/avatars/avatar-15.webp',
    email: 'charlotte.lee@example.com',
    phone: 7123456780,
    city: 'San Diego',
    notes: 'Favourite freelancer and supplier for creative deliverables.',
    addedDate: new Date('2024-06-26'),
    labels: ['freelancer', 'supplier'],
    status: 'active',
    isFavourite: true,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Benjamin',
    lastName: 'White',
    image: '/images/avatars/avatar-16.webp',
    email: 'benjamin.white@example.com',
    phone: 6123456780,
    city: 'Philadelphia',
    notes: 'Active partner and customer on the reseller program.',
    addedDate: new Date('2023-08-11'),
    labels: ['partner', 'customer'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Rachel',
    lastName: 'Green',
    image: '/images/avatars/avatar-17.webp',
    email: 'rachel.green@example.com',
    phone: 5123456780,
    city: 'Detroit',
    notes: 'Spam lead — automated sign-up with invalid company details.',
    addedDate: new Date('2024-02-19'),
    labels: ['lead'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: true
  },
  {
    firstName: 'Daniel',
    lastName: 'Scott',
    image: '/images/avatars/avatar-18.webp',
    email: 'daniel.scott@example.com',
    phone: 4123456780,
    city: 'Houston',
    notes: 'Blocked prospect supplier — compliance review pending.',
    addedDate: new Date('2023-11-25'),
    labels: ['supplier'],
    status: 'prospect',
    isFavourite: false,
    isRecent: false,
    isBlocked: true,
    isSpam: false
  },
  {
    firstName: 'Grace',
    lastName: 'Hall',
    image: '/images/avatars/avatar-19.webp',
    email: 'grace.hall@example.com',
    phone: 9876543210,
    city: 'Charlotte',
    notes: 'Enterprise customer referred through the partner network.',
    addedDate: new Date('2024-05-12'),
    labels: ['customer', 'lead'],
    status: 'active',
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Henry',
    lastName: 'Clark',
    image: '/images/avatars/avatar-20.webp',
    email: 'henry.clark@example.com',
    phone: 9765432109,
    city: 'Columbus',
    notes: 'Prospective partner for the midwest reseller program.',
    addedDate: new Date('2024-09-08'),
    labels: ['partner'],
    status: 'prospect',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Isabella',
    lastName: 'Young',
    email: 'isabella.young@example.com',
    phone: 9654321098,
    city: 'Indianapolis',
    notes: 'VIP account manager for the retail division.',
    addedDate: new Date('2023-12-03'),
    labels: ['vip', 'customer'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Jack',
    lastName: 'Wright',
    image: '/images/avatars/avatar-1.webp',
    email: 'jack.wright@example.com',
    phone: 9543210987,
    city: 'Las Vegas',
    notes: 'Spam contact — bulk promotional messages flagged by filter.',
    addedDate: new Date('2024-10-21'),
    labels: ['freelancer'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: true
  },
  {
    firstName: 'Kelly',
    lastName: 'King',
    image: '/images/avatars/avatar-2.webp',
    email: 'kelly.king@example.com',
    phone: 9432109876,
    city: 'Minneapolis',
    notes: 'Primary supplier for packaging materials.',
    addedDate: new Date('2024-02-28'),
    labels: ['supplier'],
    status: 'active',
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Lucas',
    lastName: 'Hill',
    image: '/images/avatars/avatar-3.webp',
    email: 'lucas.hill@example.com',
    phone: 9321098765,
    city: 'Tampa',
    notes: 'Blocked lead — failed identity verification during onboarding.',
    addedDate: new Date('2023-07-19'),
    labels: ['lead'],
    status: 'prospect',
    isFavourite: false,
    isRecent: false,
    isBlocked: true,
    isSpam: false
  },
  {
    firstName: 'Nora',
    lastName: 'Adams',
    image: '/images/avatars/avatar-4.webp',
    email: 'nora.adams@example.com',
    phone: 9210987654,
    city: 'Orlando',
    notes: 'Favourite VIP partner — quarterly business review scheduled.',
    addedDate: new Date('2025-04-14'),
    labels: ['partner', 'vip'],
    status: 'active',
    isFavourite: true,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Owen',
    lastName: 'Baker',
    image: '/images/avatars/avatar-5.webp',
    email: 'owen.baker@example.com',
    phone: 9109876543,
    city: 'Salt Lake City',
    notes: 'Inactive customer — account dormant since last renewal cycle.',
    addedDate: new Date('2023-04-06'),
    labels: ['customer'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Paula',
    lastName: 'Reed',
    image: '/images/avatars/avatar-6.webp',
    email: 'paula.reed@example.com',
    phone: 9098765432,
    city: 'Kansas City',
    notes: 'Freelance consultant — lead for the Q2 advisory project.',
    addedDate: new Date('2024-11-30'),
    labels: ['lead', 'freelancer'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Quinn',
    lastName: 'Turner',
    image: '/images/avatars/avatar-7.webp',
    email: 'quinn.turner@example.com',
    phone: 8987654321,
    city: 'Sacramento',
    notes: 'Spam supplier — flagged for suspicious invoice submissions.',
    addedDate: new Date('2024-06-17'),
    labels: ['supplier', 'customer'],
    status: 'prospect',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: true
  },
  {
    firstName: 'Ryan',
    lastName: 'Cooper',
    image: '/images/avatars/avatar-8.webp',
    email: 'ryan.cooper@example.com',
    phone: 8876543210,
    city: 'Cleveland',
    notes: 'Active lead from the trade show booth in March.',
    addedDate: new Date('2025-01-22'),
    labels: ['lead'],
    status: 'active',
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Samantha',
    lastName: 'Brooks',
    image: '/images/avatars/avatar-9.webp',
    email: 'samantha.brooks@example.com',
    phone: 8765432109,
    city: 'Raleigh',
    notes: 'VIP customer with dedicated account support.',
    addedDate: new Date('2024-08-14'),
    labels: ['customer', 'vip'],
    status: 'active',
    isFavourite: true,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Tyler',
    lastName: 'Foster',
    image: '/images/avatars/avatar-10.webp',
    email: 'tyler.foster@example.com',
    phone: 8654321098,
    city: 'Milwaukee',
    notes: 'Prospect freelancer — portfolio review in progress.',
    addedDate: new Date('2024-12-18'),
    labels: ['freelancer'],
    status: 'prospect',
    isFavourite: false,
    isRecent: true,
    isBlocked: false,
    isSpam: false
  },
  {
    firstName: 'Uma',
    lastName: 'Patel',
    email: 'uma.patel@example.com',
    phone: 8543210987,
    city: 'San Jose',
    notes: 'Blocked partner — contract dispute under legal review.',
    addedDate: new Date('2023-10-05'),
    labels: ['partner'],
    status: 'inactive',
    isFavourite: false,
    isRecent: false,
    isBlocked: true,
    isSpam: false
  },
  {
    firstName: 'Victor',
    lastName: 'Nguyen',
    image: '/images/avatars/avatar-11.webp',
    email: 'victor.nguyen@example.com',
    phone: 8432109876,
    city: 'Albuquerque',
    notes: 'Supplier for regional logistics and warehousing.',
    addedDate: new Date('2024-04-07'),
    labels: ['supplier', 'partner', 'customer'],
    status: 'active',
    isFavourite: false,
    isRecent: false,
    isBlocked: false,
    isSpam: false
  }
]
